In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
#Read the CSV file
df=pd.read_csv(r"C:\Users\BaBuReDdI\Downloads\traffic_stops - traffic_stops_with_vehicle_number.csv")

C:\Users\BaBuReDdI\AppData\Local\Temp\ipykernel_13028\309057140.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(r"C:\Users\BaBuReDdI\Downloads\traffic_stops - traffic_stops_with_vehicle_number.csv")

In [4]:
#Check data
df

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,0:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,0:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,0:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,0:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,0:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65533,2020-02-15,12:13:00,India,F,54,48,Black,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568
65534,2020-02-15,12:14:00,Canada,F,18,35,Hispanic,Seatbelt,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098
65535,2020-02-15,12:15:00,USA,M,27,41,Asian,Seatbelt,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328
65536,2020-02-15,12:16:00,Canada,F,49,63,Black,Seatbelt,Other,False,NaN,Warning,True,0-15 Min,True,KA24UZ8488
65537,2020-02-15,12:17:00,USA,F,72,32,Other,Seatbelt,Speeding,True,NaN,Ticket,True,16-30 Min,False,UP89PT2924

In [5]:
df.isnull().sum()

stop_date                 0
stop_time                 0
country_name              0
driver_gender             0
driver_age_raw            0
driver_age                0
driver_race               0
violation_raw             0
violation                 0
search_conducted          0
search_type           21720
stop_outcome              0
is_arrested               0
stop_duration             0
drugs_related_stop        0
vehicle_number            0
dtype: int64

In [6]:
df.isnull().sum().sum()

np.int64(21720)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65538 entries, 0 to 65537
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           65538 non-null  object
 1   stop_time           65538 non-null  object
 2   country_name        65538 non-null  object
 3   driver_gender       65538 non-null  object
 4   driver_age_raw      65538 non-null  int64
 5   driver_age          65538 non-null  int64
 6   driver_race         65538 non-null  object
 7   violation_raw       65538 non-null  object
 8   violation           65538 non-null  object
 9   search_conducted    65538 non-null  bool
 10  search_type         43818 non-null  object
 11  stop_outcome        65538 non-null  object
 12  is_arrested         65538 non-null  bool
 13  stop_duration       65538 non-null  object
 14  drugs_related_stop  65538 non-null  bool
 15  vehicle_number      65538 non-null  object
dtypes: bool(3), int64(2), object(11)
memory usage: 6.7+ MB

In [8]:
# Fill missing values
print(df['search_type'].value_counts())

search_type
Frisk             21971
Vehicle Search    21847
Name: count, dtype: int64

In [9]:
choices = ['Frisk', 'Vehicle Search ']

In [10]:
df.loc[df['search_type'].isna(), 'search_type'] = np.random.choice(
    choices,
    size=df['search_type'].isna().sum()
)

In [11]:
#To check missing values
df.isnull().sum()

stop_date             0
stop_time             0
country_name          0
driver_gender         0
driver_age_raw        0
driver_age            0
driver_race           0
violation_raw         0
violation             0
search_conducted      0
search_type           0
stop_outcome          0
is_arrested           0
stop_duration         0
drugs_related_stop    0
vehicle_number        0
dtype: int64

In [12]:
df.isnull().sum().sum()

np.int64(0)

In [13]:
# Convert date and time
df['stop_date'] = pd.to_datetime(df['stop_date'])
df['stop_time'] = pd.to_datetime(df['stop_time'])

C:\Users\BaBuReDdI\AppData\Local\Temp\ipykernel_13028\792788991.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['stop_time'] = pd.to_datetime(df['stop_time'])

In [14]:
df

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,2025-10-23 00:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,2025-10-23 00:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,2025-10-23 00:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,2025-10-23 00:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,2025-10-23 00:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65533,2020-02-15,2025-10-23 12:13:00,India,F,54,48,Black,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568
65534,2020-02-15,2025-10-23 12:14:00,Canada,F,18,35,Hispanic,Seatbelt,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098
65535,2020-02-15,2025-10-23 12:15:00,USA,M,27,41,Asian,Seatbelt,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328
65536,2020-02-15,2025-10-23 12:16:00,Canada,F,49,63,Black,Seatbelt,Other,False,Frisk,Warning,True,0-15 Min,True,KA24UZ8488
65537,2020-02-15,2025-10-23 12:17:00,USA,F,72,32,Other,Seatbelt,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,False,UP89PT2924

In [15]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in .\.venv\lib\site-packages (9.4.0)
Note: you may need to restart the kernel to use updated packages.

In [16]:
import mysql.connector

In [17]:
from datetime import datetime

In [18]:
import pandas as pd

In [19]:
# SQL Database Connection
mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="ashu",
    auth_plugin='mysql_native_password'
)

In [20]:
#Create cursor
mycursor = mydb.cursor()

In [21]:
print("Connection successful!")

Connection successful!

In [22]:
#Create Database
mycursor.execute("CREATE DATABASE secure_check")

In [23]:
#USE Database
mycursor.execute("USE secure_check")

In [24]:
#Create Table
create_table_query = """ 
CREATE TABLE IF NOT EXISTS policelog (
    stop_date DATETIME,
    stop_time DATETIME,
    country_name VARCHAR(200),
    driver_gender VARCHAR(10),
    driver_age_raw INT,
    driver_age INT,
    driver_race VARCHAR(200),
    violation_raw VARCHAR(200),
    violation VARCHAR(200),
    search_conducted VARCHAR(200),
    search_type VARCHAR(200),
    stop_outcome VARCHAR(200),
    is_arrested BOOLEAN,
    stop_duration VARCHAR(200),
    drugs_related_stop BOOLEAN,
    vehicle_number VARCHAR(200)
)
"""

In [25]:
mycursor.execute(create_table_query)
print("Table created sucessfully")

Table created sucessfully

In [26]:
#SQL insert Query
insert_query = """
INSERT INTO policelog (
    stop_date, stop_time, country_name, driver_gender, driver_age_raw, driver_age,
    driver_race, violation_raw, violation, search_conducted, search_type,
    stop_outcome, is_arrested, stop_duration, drugs_related_stop, vehicle_number
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

In [27]:
#Process DataFrame 
df['stop_time'] = pd.to_datetime(df['stop_time'], errors='coerce').dt.time
df['stop_date'] = pd.to_datetime(df['stop_date'], errors='coerce')

In [28]:
# Insert each row 
for index, row in df.iterrows():
    stop_datetime = None
    if pd.notnull(row['stop_date']) and pd.notnull(row['stop_time']):
        stop_datetime = f"{row['stop_date'].strftime('%Y-%m-%d')} {row['stop_time'].strftime('%H:%M:%S')}"

    mycursor.execute(insert_query, (
        row['stop_date'].strftime('%Y-%m-%d %H:%M:%S') if pd.notnull(row['stop_date']) else None,
        stop_datetime,
        row['country_name'],
        row['driver_gender'],
        row['driver_age_raw'],
        row['driver_age'],
        row['driver_race'],
        row['violation_raw'],
        row['violation'],
        row['search_conducted'],
        row['search_type'],
        row['stop_outcome'],
        row['is_arrested'],
        row['stop_duration'],
        row['drugs_related_stop'],
        row['vehicle_number']
    ))

In [29]:
# Commit Changes
mydb.commit()
print("All records inserted successfully!")

All records inserted successfully!

In [30]:
# Close Connection
mycursor.close()
mydb.close()